<style type="text/css"><!--
.default_setting {
	color:#009900;
	font-weight:bold;
	}
.custom_setting {
	color:#990099;
	font-weight:bold;
	}
.navbar,.fdtan,.t {
	background-color:#d5d2bb;
	}
.g,.grey {
	background-color:#eeeeee;
	}
.fdblue,th,.b {
	background-color:#9eb3c7;
	}
body.t {
	margin-top:0px;
	}
body,p,dl,dt,dd,td,th,li,ul,ol {
	font-family:verdana;
	font-size:10pt;
	}
textarea,input {
	font-family:monospace;
	}
input.submit {
	font-family:verdana;
	background-color:#ffffff;
	cursor:pointer;
	cursor:hand;
	font-weight:bold;
	}
a.onblue {
	color:#000000;
	}
a {
	color:#cc0000;
	}
a:hover {
	color: #ff4444;
	}
.existing_data {
	background-color:#cccccc;
	}
//--></style>